title: DiSCo Network
author:
  name: DiSCo
  email: ''
metadata:
    description: 'DiSCo Network is '
    
footer:
  tone: dark
  title: "Contact & links"
  enquiries_email: "editors.discojournal@gmail.com"
  mailing_list_url: "https://discojournal.us8.list-manage.com/subscribe?u=5ab368fdf3daa3139b2abe749&id=68094b5235"
  instagram_url: "https://www.instagram.com/discojournal/"
  instagram_handle: "@discojournal"


